### ISSUE TITLE
Feature Request: Obsidian links on metadata.

### ISSUE THREAD

**Issue by EhuddR** [arnau/obsidian-metatable#3]
Hi! I was wonder if you can add the posibility of make clickables obsidian Links on metadata. I think this is not possible but it would be a pretty cool feature. 

`---`
`tags: #literature`
`author: [[Noam Chomsky]]` 
`---`

**Comment by arnau** [comment]
I haven't seen anything that suggests you can in the API but I agree it would be a great addition.

**Comment by arnau** [comment]
Hi @EhuddR, the new 0.7.0 adds a flag in settings for autolinks. See https://github.com/arnau/obsidian-metatable/tree/0.7.0#autolinks

You'll notice that your example:

```yaml
---
tags: #literature
author: [[Noam Chomsky]]
---
```

won't work because the `[]` are reserved characters in YAML. Instead you can do:

```yaml
---
tags: literature
author: "[[Noam Chomsky]]"
---
```

Or

```yaml
---
tags: literature
author: %Noam Chomsky%
---
```
