### ISSUE TITLE
Format dates that appear in ugly RFC/ISO format

### ISSUE THREAD

**Issue by xplosionmind** [arnau/obsidian-metatable#43]
All of my notes contain creation and modification date in the front matter. Such dates are handled automatically by other plugins, and they are written in ISO 8601 / RFC 3339 date & time format.

```yaml
---
# example
date: 2021-12-27T02:20:03+01:00
updated: 2023-01-04T16:46:56+01:00
---
```

It would be awesome if metatable could show them in a nicer, more human-readable format (without changing the source date, of course)
