### ISSUE TITLE
Message: "Nested mappings are not allowed"

### ISSUE THREAD

**Issue by badarotti** [arnau/obsidian-metatable#52]
Hi, Thanks for the great plugin. Seems like it will improve the quality of using Obsidian a great deal.

I'm getting the following error message on one of my notes:

```
Nested mappings are not allowed in compact mappings at line 4, column 9:

author: qBittorrent Development Team: https://github.com/qbittorrent
        ^
```

... from the following frontmatter:

```
created: 2023-06-30 - 19:50 
tags: 
url: https://www.qbittorrent.org/
author: qBittorrent Development Team: https://github.com/qbittorrent
```

The `^` seems to be pointing the letter number 9 `q` in the `author` attribute but I don't think that's the issue.

The problem seem to go away when I remove the colon in `Team:`, but I see the the colon is used no problem  in other attributes.

Is this a bug or am I missing something?

Thanks

**Comment by arnau** [comment]
By the looks of it, you are missing some quotes. In YAML a value containing a reserved sequence such as `: ` (notice space after `:` has to be "escaped" e.g. by adding quotes:

```yaml
created: 2023-06-30 - 19:50 
tags: 
url: https://www.qbittorrent.org/
author: "qBittorrent Development Team: https://github.com/qbittorrent"
```

Hope this helps
