### ISSUE TITLE
Hide the metadata in Embedded Notes

### ISSUE THREAD

**Issue by avinashkanaujiya** [arnau/obsidian-metatable#53]

**Comment by avinashkanaujiya** [comment]
It make the page look crowded, when multiple pages with metadata is embedded,

**Comment by arnau** [comment]
Thanks for the suggestion, it's definitely something to explore. I haven't delved into how embedded notes work.

**Comment by arnau** [comment]
FYI, you can get this solved using a bit of custom CSS:

```css
.internal-embed .obsidian-metatable {
  display: none;
}
```
